/* 🤖 this file was generated by svg-to-ts*/
export const svgIconVitagroupSignet: {
  name: 'vitagroup-signet';
  data: string;
} = {
  name: 'vitagroup-signet',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2670.42 2359.09"><path d="M1490.82 2359.09c651.48 0 1179.6-528.04 1179.6-1179.59C2670.42 528.219 2142.3 0 1490.82 0l338.99 1194.91-338.99 1164.18M0 2359.09c651.648 0 1179.67-528.04 1179.67-1179.59C1179.67 528.219 651.648 0 0 0l339.082 1194.91L0 2359.09"/></svg>`
};
export type AppIconNames = 'vitagroup-signet';
export interface AppIcon {
  name: AppIconNames;
  data: string;
}
export type AppIconNameSubset<
  T extends Readonly<AppIcon[]>
> = T[number]['name'];
