import { setCompodocJson } from '@storybook/addon-docs/angular';

// auto-generated by compodoc, see npm package scripts section
// make sure to run any desired json generation task before serving or building the storybook application. you can
// also start the respective scripts in watch mode to continuously receive updated json content
// e.g. `npm run pds-components:json -- -w`
import * as jsonDocs from '../../../packages/pds-components/documentation.json';

setCompodocJson(jsonDocs);

export const parameters = {
  // layout: 'centered',
  options: {
    storySort: {
      order: ['Getting Started', 'PDS CSS', ['Intro', '*'], 'PDS Components', '*'],
    },
  },
};
